Bump `swiftformat`, `swiftlint` and fix violations (#1485)
### Changelog
None
### Docs

None
### Description
There's no point declaring a class method `public` if the class itself
isn't.

```
~/Code/forks/mcap (main) docker run -t --rm -v $(pwd):/work ghcr.io/nicklockwood/swiftformat:0.58.6 --lint /work
Running SwiftFormat...
(lint mode - no files will be changed.)
Reading config file at /work/.swiftformat
/work/swift/mcap/RecordReader.swift:29:1: error: (redundantPublic) Remove redundant public access control from declarations in internal or private types.
/work/swift/mcap/RecordReader.swift:41:1: error: (redundantPublic) Remove redundant public access control from declarations in internal or private types.
/work/swift/conformance/ReadConformanceRunner.swift:109:1: error: (redundantPublic) Remove redundant public access control from declarations in internal or private types.
/work/swift/conformance/ReadConformanceRunner.swift:117:1: error: (redundantPublic) Remove redundant public access control from declarations in internal or private types.
SwiftFormat completed in 0.62s.
Source input did not pass lint check.
2/15 files require formatting, 39 files skipped.
```